import { z } from "zod";

// Unified Entry schema with type-specific metadata
export const EntrySchema = z.object({
  id: z.string().uuid().optional(), // PostgreSQL will generate this
  userId: z.string(), // From Clerk authentication
  type: z.enum(["article", "company", "note"]),
  url: z.string().url().optional(), // Optional for notes
  createdAt: z.date().optional(), // Generated by database
  updatedAt: z.date().optional(), // Generated by database
  metadata: z.object({
    // Common metadata fields
    title: z.string(),
    summary: z.string().optional(),
    keyPoints: z.array(z.string()).optional(),
    
    // Type-specific fields
    // For articles
    author: z.string().optional(),
    publishedDate: z.string().optional(),
    
    // For companies
    companyName: z.string().optional(),
    industry: z.string().optional(),
    competitiveLandscape: z.string().optional(),
    
    // For notes
    text: z.string().optional(),
    
    // Vector embedding for similarity search
    embedding: z.array(z.number()).optional(),
  }),
});

export const CommentSchema = z.object({
  id: z.string().uuid().optional(), // PostgreSQL will generate this
  userId: z.string(), // From Clerk authentication
  entryId: z.string().uuid(), // Reference to an Entry
  text: z.string(),
  createdAt: z.date().optional(), // Generated by database
});

export type Entry = z.infer<typeof EntrySchema>;
export type Comment = z.infer<typeof CommentSchema>;
