import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full border-b px-6 py-3 mb-8 bg-white">
          <div className="max-w-2xl mx-auto">
            <a href="/" className="font-bold text-xl tracking-tight text-blue-700 hover:text-blue-900 transition-colors">
              Satchel
            </a>
          </div>
        </header>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
